assect/urls.py
from django.contrib import admin
from django.urls import path, include

from base import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.index, name='home'),
    path('hr/', include('hr.urls')),
    path('att/', include('attendance.urls')),

    path('conf/', views.config),
    path('corpid/', views.create_corpid),

    path('sign/', views.sign_view),
    path('signout/', views.signout),
]

attendance/urls.py
from django.urls import path

from . import views

app_name = 'attendance'
urlpatterns = [
    path('', views.index, name='index'),

    path('attendance/', views.attendance, name='attendance'),
    path('attclass/', views.attclass, name='attclass'),
    path('holiday/', views.attholiday, name='holiday'),
    path('summary/', views.summary, name='summary'),
    path('att_collect_detail/', views.att_collect_detail, name='collect'),

    path('confatt/', views.configatt, name='config'),

    path('inputxml/', views.inputxml),
    path('checkbody/', views.checkeveryday),
    path('getmssql/', views.getmssql),
    path('getmssqlpin/', views.getmssqlpin),
    path('cmpcheck/', views.cmpcheck),
]

hr/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),

    path('hr/', views.hr_list, name='employee'),
    path('hrdetailed/', views.hr_detailed, name='employee_detailed'),
    path('dep/', views.dep_list, name='department'),

    path('confbase/', views.confbase_view, name='config_base'),
    path('confmore/', views.confmore_view, name='config_more'),

    path('syncfromwx/', views.wx_syncfromwx),
    path('corpsecret/', views.wx_corpsecret_save),
]

hr/models.py
from django.db import models

# Create your models here.
# ==================员工表==================


class hrconfigs(models.Model):
    # 人力资源配置表
    name = models.CharField(max_length=32, null=True, verbose_name='配置名称')

    class Meta:
        db_table = 'hr_hrconfigs'


class department(models.Model):
    # 部门表
    pid = models.IntegerField(unique=True)
    name = models.CharField(max_length=32, null=False, verbose_name='名称')
    parentid = models.IntegerField(default=0, verbose_name='上级部门')
    order = models.IntegerField(null=True, verbose_name="次序")
    # 组织类型:0行政，1项目，2团队，3组织标签
    type = models.IntegerField(default=0, verbose_name='组织类型')
    wxsync = models.BooleanField(default=False, verbose_name="同步企业微信")

    class Meta:
        db_table = 'hr_department'


class employee(models.Model):
    # 员工表employee
    userid = models.CharField(unique=True, max_length=64, verbose_name='用户ID')
    employeeno = models.CharField(max_length=12, null=True, blank=True, verbose_name='员工编号')
    entry = models.DateField(null=True, blank=True, verbose_name='入职')
    leave = models.DateField(null=True, blank=True, verbose_name='离职')
    name = models.CharField(max_length=64, verbose_name='姓名')
    alias = models.CharField(null=True, blank=True, max_length=32, verbose_name='别名')
    department = models.CharField(null=True, blank=True, max_length=256, verbose_name='部门')
    position = models.CharField(null=True, blank=True, max_length=64, verbose_name='职务信息')
    mobile = models.CharField(null=True, blank=True, max_length=16, verbose_name='手机')
    # 性别，1    表示男性，2    表示女性
    gender = models.CharField(null=True, blank=True, max_length=16, verbose_name='姓别')
    email = models.EmailField(null=True, blank=True, verbose_name='邮箱')
    # 头像url。注：如果要获取小图将url最后的”/0”改成”/100”即可。
    avatar = models.CharField(null=True, blank=True, max_length=256, verbose_name='头像')
    # 激活状态：1 = 已激活    2 = 已禁用    4 = 未激活    已激活代表已激活企业微信或已关注微工作台（原企业号）
    status = models.IntegerField(default=1, verbose_name="激活状态")
    # 成员启用状态。1表示启用的成员，0表示被禁用。服务商调用接口不会返回此字段
    enable = models.IntegerField(default=1, verbose_name="有效")
    # 上级字段，标识是否为上级。0表示普通成员，1表示上级
    isleader = models.IntegerField(default=0, verbose_name='主管')
    extattr = models.CharField(null=True, blank=True, max_length=256, verbose_name='扩展属性')
    hide_mobile = models.BooleanField(default=0, verbose_name='隐蔽手机')
    english_name = models.CharField(null=True, blank=True, max_length=64, verbose_name='英文名')
    telephone = models.CharField(null=True, blank=True, max_length=16, verbose_name='座机')
    order = models.CharField(null=True, blank=True, max_length=256, verbose_name='部门内的排序值')
    external_profile = models.CharField(null=True, blank=True, max_length=1024, verbose_name='成员对外属性')
    qr_code = models.CharField(null=True, blank=True, max_length=256, verbose_name='个人二维码')
    address = models.CharField(null=True, blank=True, max_length=128, verbose_name='地址')
    passwd = models.CharField(max_length=256, null=True, blank=True, verbose_name='密码')
    session = models.CharField(max_length=32, null=True, blank=True, verbose_name='Cookice_session')
    expsession = models.TimeField(null=True, blank=True)
    # 是否同步企业微信，F未同步，T已同步
    wxsync = models.BooleanField(default=0, verbose_name="同步企业微信")
    active = models.BooleanField(default=True, verbose_name='有效的')

    class Meta:
        db_table = 'hr_employee'


class extprivate(models.Model):
    employee_id = models.ForeignKey('employee', to_field='id', on_delete=models.CASCADE, related_name='privateid', verbose_name='员工ID')
    code = models.CharField(max_length=20, null=True, blank=True, verbose_name='身份证号')
    nationality = models.CharField(max_length=20, null=True, blank=True, verbose_name='国籍')
    nation = models.CharField(max_length=20, null=True, blank=True, verbose_name='民族')
    nationplace = models.CharField(max_length=20, null=True, blank=True, verbose_name='籍贯')
    birthday = models.DateField(verbose_name='生日')
    height = models.IntegerField(null=True, blank=True, verbose_name='身高')
    weight = models.IntegerField(null=True, blank=True, verbose_name='体重')
    blood = models.CharField(max_length=2, null=True, blank=True, verbose_name='血型')
    marital = models.BooleanField(default=False, verbose_name='婚姻')

    class Meta:
        db_table = 'hr_extprivate'


class extattr(models.Model):
    # 扩展属性
    empid = models.ForeignKey('employee', to_field='id', on_delete=models.CASCADE, related_name='employeeid', verbose_name='员工ID')
    # 类型 0：文本 1：网址 2：小程序
    type = models.IntegerField(default=0, verbose_name='类型')
    # 名称
    name = models.TextField(max_length=64, null=True, blank=True, verbose_name='名称')
    # 值
    value = models.TextField(max_length=256, null=True, blank=True, verbose_name='文本')
    url = models.TextField(max_length=256, null=True, blank=True, verbose_name='网址')
    title = models.CharField(max_length=64, null=True, blank=True, verbose_name='标题')

    class Meta:
        db_table = 'hr_extattr'


class employee_department(models.Model):
    # 员工部门关系表
    employeeid = models.ForeignKey('employee', to_field='userid', on_delete=models.CASCADE, verbose_name='员工ID')
    departmentid = models.ForeignKey('department', to_field='pid', on_delete=models.CASCADE, verbose_name='部门ID')
    isleader = models.BooleanField(default=0, verbose_name='负责人')

    class Meta:
        db_table = 'hr_employee_department'


class user_sign_log(models.Model):
    # 用户登录日志
    signtime = models.DateTimeField(verbose_name='登录时间')
    employeeid = models.ForeignKey('employee', on_delete=models.CASCADE, verbose_name='员工ID')
    fromip = models.CharField(max_length=16, verbose_name='来源IP')
    contl = models.CharField(max_length=32, verbose_name='描述或登录方式')

    class Meta:
        db_table = 'hr_user_sign_log'

hr/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db.models import Avg, Sum, Max, Min, Count

import requests
import json
import datetime

from base.models import configs, wxsecret
from hr.models import hrconfigs, employee, department, employee_department
from attendance.models import checkinout

from . import wxdef

# Create your views here.
def index(request):
    return redirect('/hr/hr/')


def hr_list(request):
    context = {}
    context['title'] = '人员'

    username = request.COOKIES.get('usercookie', None)
    if username:
        try:
            signuser = employee.objects.get(session=username)
        except Exception:
            context['userinfo'] = '用户'
            return redirect('/sign/')
        context['userinfo'] = signuser.name
    else:
        context['userinfo'] = '用户'
        return redirect('/sign/')

    # d = base_conf.objects.all().first()
    # ps = hr_department.objects.all().order_by('parentid','order')
    # ps = hr_department.objects.filter(parentid=1).order_by('pid', 'order')
    ps = employee.objects.filter(active=True).values().order_by('name')
    context['context'] = ps
    return render(request, 'hr_employee_list.html', context)


def hr_detailed(request):
    context = {}
    context['title'] = '人员'

    username = request.COOKIES.get('usercookie', None)
    if username:
        try:
            signuser = employee.objects.get(session=username)
        except Exception:
            context['userinfo'] = '用户'
            return render(request, 'sign.html', context)
        context['userinfo'] = signuser.name
    else:
        context['userinfo'] = '用户'
        return render(request, 'sign.html', context)

    if request.method == "GET":
        print(request.GET)
        if "id" in request.GET:
            empid = int(request.GET['id'])

            ps = employee.objects.filter(pk=empid).values('name',
                                                          'position',
                                                          'mobile',
                                                          'email',
                                                          'address',
                                                          'telephone',
                                                          'extemployeeatt__pin',
                                                          'userid').first()

            # ==============================
            # count_data = storage_log.objects.filter(CreateTime__year=this_year, CreateTime__month=this_month)\
            #     .extra(select={"CreateTime": "DATE_FORMAT(CreateTime,'%%e')"})\
            #     .values('CreateTime')\
            #     .annotate(send_num=Count('CreateTime'))\
            #     .values('CreateTime', 'count_len')

            e = ps['extemployeeatt__pin']
            print(e)
            attch = checkinout.objects.filter(pin=e, checktime__year=2016, checktime__month=9)\
                .values('pin', 'checktime')\
                .order_by('checktime')

            # attch = checkinout.objects.filter(pin=e).values_list('checktime')
            print(attch)
            print(len(attch))
            # ================================

            emps = employee_department.objects.filter(employeeid=ps['userid']).values('id', 'departmentid__name')
            ps['emps'] = emps

            department_isleaders = employee_department.objects.filter(isleader=True, employeeid=ps['userid']).values('id',
                                                                                                                     'departmentid__name')
            ps['dep_isleaders'] = department_isleaders
            context['context'] = ps

            print("======")
            print(context)
            return render(request, 'hr_employee_detailed.html', context)

    elif request.method == "POST":
        if "act" in request.POST:
            if request.POST['act'] == "create":
                pass


def dep_list(request):
    context={}
    context['title'] = '部门'

    username = request.COOKIES.get('usercookie', None)
    if username:
        try:
            signuser = employee.objects.get(session=username)
        except Exception:
            context['userinfo'] = '用户'
            return render(request, 'sign.html', context)
        context['userinfo'] = signuser.name
    else:
        context['userinfo'] = '用户'
        return render(request, 'sign.html', context)

    if request.method == "GET":
        ps = department.objects.filter(type=0)\
            .values('id', 'pid', 'name', 'parentid')\
            .order_by('pid')
        context['context'] = ps

        deps = []
        for k in ps:
            # 查找负责人
            leaders = employee_department.objects.filter(isleader=True, departmentid=k['pid'])\
                .values('id', 'employeeid__name')
            if leaders is None:
                pass
            else:
                k['leaders'] = leaders

            # 查找部门员工
            employeecount = employee_department.objects.filter(departmentid=k['pid'])\
                .values('departmentid_id')\
                .annotate(employeesum=Count('id'))
            # print(k['name'])
            # print(employeecount)
            if employeecount:
                k['employeenum'] = employeecount[0]['employeesum']
            else:
                k['employeenum'] = 0

            # 查找子部门
            departmentcount = department.objects.filter(parentid=k['pid'])\
                .values('parentid')\
                .annotate(departmentsum=Count('id'))
            # print(k['name'])
            # print(departmentcount)
            if departmentcount:
                k['departmentsum'] = departmentcount[0]['departmentsum']
            else:
                k['departmentsum'] = 0

            deps.append(k)
        context['context'] = deps

        parents = department.objects.all().order_by('name')
        context['parents'] = parents

        employees= employee.objects.filter(active=True).order_by('name')
        context['employees'] = employees
        return render(request, 'hr_department_list.html', context)

    elif request.method == "POST":
        print(request.POST)
        data = {}
        if "act" in request.POST:
            if request.POST['act'] == "create":
                # 查找可用Pid
                pidmax = department.objects.all().values('pid').order_by('pid').last()
                pida = pidmax['pid'] + 1
                # 查找上一级
                parentinp = int(request.POST['parent'])
                if parentinp:
                    mparentobj = department.objects.get(id=parentinp)
                    mparentid = mparentobj.pid
                else:
                    mparentid = 0
                # 查找平级，取order值
                ordermax = department.objects.filter(parentid=parentinp)\
                    .values()\
                    .order_by('-order')\
                    .first()
                if ordermax is None:
                    ordera = 100000000
                else:
                    ordera = ordermax['order'] + 1
                # 新建到数据库
                nitem = department(pid=pida,
                                   name=request.POST['name'],
                                   parentid=mparentid,
                                   order=ordera,
                                   type=0)
                nitem.save()
                # 查找负责人
                leaderinp = int(request.POST['leader'])
                if leaderinp:
                    leaderid = employee.objects.get(id=leaderinp)

                # 是否要同步
                syncwx = wxsecret.objects.filter(agentid=1)
                if syncwx:
                    # 同步到企业微信
                    print(pida)
                    nwxdep = department.objects.filter(pid=pida).values()
                    print(nwxdep)
                    wxmsg=wxdef.depcreate(nwxdep.first())
                    data = json.dumps(wxmsg)
                    return HttpResponse(data, content_type="application/json")
            elif request.POST['act'] == "update":
                print('update')
            elif request.POST['act'] == "delete":
                dpid = int(request.POST['pid'])
                # 确认是否还有子内容，如有返回报错
                findsubs = department.objects.filter(parentid=dpid)
                print(findsubs)
                if findsubs:
                    data['code'] = 402
                    data['msg'] = 'Fail'
                    data['data'] = "部门下含有子部门，删除失败。"
                    data = json.dumps(data)
                    return HttpResponse(data, content_type="application/json")
                else:
                    findemps = employee_department.objects.filter(departmentid=dpid)
                    if findemps:
                        data['code'] = 403
                        data['msg'] = 'Fail'
                        data['data'] = "部门下含有员工，删除失败。"
                        data = json.dumps(data)
                        return HttpResponse(data, content_type="application/json")
                    else:
                        # 没有子内容，可以删除
                        ps = department.objects.filter(pid=dpid)
                        ps.delete()
                        data['code'] = 0
                        data['msg'] = "OK"
                        data['data'] = None
                        data = json.dumps(data)

                        #  删除同步到企业微信
                        # 是否要同步
                        syncwx = wxsecret.objects.filter(agentid=1)
                        if syncwx.exists():
                            # 同步到企业微信
                            wxmsg = wxdef.depdelete(dpid)
                            data = json.dumps(wxmsg)
                        return HttpResponse(data, content_type="application/json")
        return render(request, 'hr_department_list.html', context)


def confbase_view(request):
    context={}
    context['title'] = '常规设置'

hr/templates/hr_conf_base.html
{% extends "base.html" %}

{% block styecss %}
    <link rel="stylesheet" type="text/css" href="/static/css/hr/view_hr_list.css">
{% endblock styecss %}

{% block mainbody %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-2 border-right">
                {% include 'hr_sub_sidemenu.html' %}
            </div>
            <div class="col-10">
                <div class="row border-bottom mb-3">
                    <div class="col-12">
                        <div class="row">
                            <h3 class="col-sm-6">{{ title }}</h3>
                        </div>
                        <div class="row mb-2">
                            <div class="col-12">
                                <button type="button" class="btn btn-primary" data-toggle="create" id="kkkk">保存</button>
                                <button type="button" class="btn btn-outline-secondary disabled" data-toggle="del">返回</button>
                            </div>
                        </div>
                    </div>
                </div>
                <article class="row">
                    <div class="col-12">
                        <div class="row mb-3">
                            <div class="col-12">
                                <h5 class="text-info">常规</h5>
                            </div>
                        </div>
                        <div class="row mb-2">
                                <div class="col-2 border-right mr-3">表单日志</div>
                                <div class="custom-control custom-radio col-2">
                                    <input type="radio" class="form-check-input" id="synctype1" name="synctype">
                                    <label for="synctype1" class="form-check-label">显示日志</label>
                                </div>
                                <div class="custom-control custom-radio col-2">
                                    <input type="radio" class="form-check-input" id="synctype2" name="synctype">
                                    <label for="synctype2" class="form-check-label">不显示日志</label>
                                </div>
                            </div>
                    </div>
                </article>
            </div>
        </div>
    </div>
    {% include 'hr_sub_toast.html' %}
{% endblock %}

{% block jquery %}
        <script src="/static/js/hr/view_hr_broad.js"></script>
{% endblock jquery%}

hr/templates/hr_conf_more.html
{% extends "base.html" %}

{% block styecss %}
    <link rel="stylesheet" type="text/css" href="/static/css/hr/view_hr_list.css">
{% endblock styecss %}

{% block mainbody %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-2 border-right">
                {% include 'hr_sub_sidemenu.html' %}
            </div>
            <div class="col-10">
                <div class="row border-bottom mb-3">
                    <div class="col-12">
                        <div class="row">
                            <h3 class="col-sm-6">{{ title }}</h3>
                        </div>
                        <div class="row mb-2">
                            <div class="col-12">
                                <button type="button" class="btn btn-primary" data-toggle="create" id="kkkk">保存</button>
                                <button type="button" class="btn btn-outline-secondary disabled" data-toggle="del">返回</button>
                            </div>
                        </div>
                    </div>
                </div>
                <article class="row">
                    <div class="col-12">
                        <div class="row mb-3">
                            <div class="col-12">
                                <h5 class="text-info">高级</h5>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-12">
                                <h5 class="text-info">权限</h5>
                                <div class="form-group row mb-2">
                                    <label for="pe" class="col-2 col-form-label border-right">员工</label>
                                    <div class="col-4">
                                        <select type="" class="form-control form-control-sm" id="pe" placeholder="CRID"></select>
                                    </div>
                                </div>
                                <div class="form-group row mb-2">
                                    <label for="pe" class="col-2 col-form-label border-right">经理</label>
                                    <div class="col-4">
                                        <select type="" class="form-control form-control-sm" id="pe" placeholder="CRID"></select>
                                    </div>
                                </div>
                                <div class="form-group row mb-2">
                                    <label for="pe" class="col-2 col-form-label border-right">薪酬</label>
                                    <div class="col-4">
                                        <select type="" class="form-control form-control-sm" id="pe" placeholder="CRID"></select>
                                    </div>
                                </div>
                                <div class="form-group row mb-2">
                                    <label for="pe" class="col-2 col-form-label border-right">管理</label>
                                    <div class="col-4">
                                        <select type="" class="form-control form-control-sm" id="pe" placeholder="CRID"></select>
                                    </div>
                                </div>

                            </div>
                        </div>

                        <div class="row mb-3">

                            <div class="col-12">
                                <h5 class="text-info">企业微信</h5>
                                <div class="form-group row mb-2">
                                    <label for="inputEmail3" class="col-2 col-form-label border-right">微信同步码</label>
                                    <div class="input-group col-5">
                                        <input type="text" class="form-control " id="inputcrid" placeholder="CRID" aria-describedby="button-crid" value="uUJf-eFplyKlAWf2Cc9T8Guea4K1zpEiZXwXpCsHTQs">
                                        <div class="input-group-append">
                                            <button class="btn btn-outline-info" type="button" id="save-crid"><i class="fa fa-download" aria-hidden="true"></i></button>
                                        </div>
                                    </div>
                                </div>

                                <div class="row mb-2">
                                    <div class="col-2 border-right mr-3">同步方式</div>
                                    <div class="custom-control custom-radio col-2">
                                        <input type="radio" class="custom-control-input" id="synctype1" name="synctype">
                                        <label for="synctype1" class="custom-control-label">自动同步</label>
                                    </div>
                                    <div class="custom-control custom-radio col-2">
                                        <input type="radio" class="custom-control-input" id="synctype2" name="synctype">
                                        <label for="synctype2" class="custom-control-label">手动同步</label>
                                    </div>
                                </div>
                                <div class="row mb-2">
                                    <div class="col-2 border-right">获取数据</div>
                                    <div class="col">
                                        <p>从企业微信中获取人员和部门信息，替换现有员工及部门数据</p>
                                        <button class="btn btn-outline-info btn-sm" data-action="syncfromwx"><i class="fa fa-cloud-download fa-1x"></i>获取数据</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </article>
            </div>
        </div>
    </div>
</div>
{% include 'hr_sub_toast.html' %}
{% endblock %}

{% block jquery %}
        <script src="/static/js/hr/conf_more.js"></script>
{% endblock jquery%}

hr/templates/hr_sub_sidemenu.html
<nav class="col-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky accordion" id="sidemenuhr">
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-primary">
            <span><i class="fa fa-users fa-1x"></i> 员工</span>
            <a class="d-flex align-items-center text-muted" href="#" >
                <i class="fa fa-plus fa-1x"></i>
            </a>
        </h6>
        <ul class="nav flex-column">
            <li class="nav-item d-flex justify-content-between align-items-center px-3">
                <a class="nav-link" href="{% url 'employee' %}">员工</a>
            </li>
            <li class="nav-item d-flex justify-content-between align-items-center px-3">
                <a class="nav-link" href="{% url 'department' %}">部门</a>
            </li>
        </ul >
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-primary">
            <span><i class="fa fa-map-marker fa-1x"></i> 考勤</span>
            <a class="d-flex align-items-center text-muted" href="#">
                <i class="fa fa-plus fa-1x"></i>
            </a>
        </h6>
        <ul class="nav flex-column">
            <li class="nav-item d-flex justify-content-between align-items-center px-3">
                <a class="nav-link" href="{% url 'attendance:index' %}">签到</a>
            </li>
            <li class="nav-item d-flex justify-content-between align-items-center px-3">
                <a class="nav-link" href="{% url 'attendance:summary' %}">出勤</a>
            </li>
            <li class="nav-item d-flex justify-content-between align-items-center px-3">
                <a class="nav-link" href="{% url 'attendance:attclass' %}">排班</a>
            </li>
            <li class="nav-item d-flex justify-content-between align-items-center px-3">
                <a class="nav-link" href="{% url 'attendance:holiday' %}">假期</a>
            </li>
        </ul >
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-primary">
            <span><i class="fa fa-cog fa-1x"></i> 设置</span>
            <a class="d-flex align-items-center text-muted" href="#">
                <i class="fa fa-plus fa-1x"></i>
            </a>
        </h6>
        <ul class="nav flex-column">
            <li class="nav-item d-flex justify-content-between align-items-center px-3">
                <a class="nav-link"  href="{% url 'attendance:config' %}">考勤</a>
            </li>
            <li class="nav-item d-flex justify-content-between align-items-center px-3">
                <a class="nav-link"  href="{% url 'config_base' %}">常规</a>
            </li>
            <li class="nav-item d-flex justify-content-between align-items-center px-3">
                <a class="nav-link"  href="{% url 'config_more' %}">高级</a>
            </li>
        </ul>
    </div>
</nav>

hr/templates/hr_sub_toast.html
<div aria-live="polite" aria-atomic="true" style="position: absolute; min-height: 200px; top: 60px; right: 10px;" class="position-fixed">
    <!-- Position it -->
    <div style="position: relative; top: 0; right: 0;">
        <!-- Then put toasts within -->
        <div class="toast" role="status" aria-live="polite" aria-atomic="true" id="showtoast" data-delay="3000">
            <div class="toast-header bg-success text-white">
                <i class="fa fa-dot-circle-o mr-2" aria-hidden="true"></i>
                <strong class="mr-auto" id="toast-title">标题</strong>
                <small class="text-white sr-only">just now</small>
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="toast-body" id="toast-msg">
                显示的信息
            </div>
        </div>
    </div>
</div>