assect/urls.py
from django.contrib import admin
from django.urls import path, include

from base import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.index, name='home'),
    path('hr/', include('hr.urls')),
    path('att/', include('attendance.urls')),

    path('conf/', views.config),
    path('corpid/', views.create_corpid),

    path('sign/', views.sign_view),
    path('signout/', views.signout),
]

attendance/urls.py
from django.urls import path

from . import views

app_name = 'attendance'
urlpatterns = [
    path('', views.index, name='index'),

    path('attendance/', views.attendance, name='attendance'),
    path('attclass/', views.attclass, name='attclass'),
    path('holiday/', views.attholiday, name='holiday'),
    path('summary/', views.summary, name='summary'),
    path('att_collect_detail/', views.att_collect_detail, name='collect'),

    path('confatt/', views.configatt, name='config'),

    path('inputxml/', views.inputxml),
    path('checkbody/', views.checkeveryday),
    path('getmssql/', views.getmssql),
    path('getmssqlpin/', views.getmssqlpin),
    path('cmpcheck/', views.cmpcheck),
]

hr/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),

    path('hr/', views.hr_list, name='employee'),
    path('hrdetailed/', views.hr_detailed, name='employee_detailed'),
    path('dep/', views.dep_list, name='department'),

    path('confbase/', views.confbase_view, name='config_base'),
    path('confmore/', views.confmore_view, name='config_more'),

    path('syncfromwx/', views.wx_syncfromwx),
    path('corpsecret/', views.wx_corpsecret_save),
]

attendance/models.py
from django.db import models

# from hr.models import employee, employee_department
# Create your models here.

class extemployeeatt(models.Model):
    # 员工PIN
    employeeid = models.ForeignKey('hr.employee', on_delete=models.CASCADE, verbose_name='员工ID')
    pin = models.CharField(max_length=20, blank=True, null=True, verbose_name='pin')

    class Meta:
        db_table = 'att_extemployeeatt'


class holiday(models.Model):
    # 节日
    holidayname = models.CharField(max_length=20, verbose_name='节日名')
    starttime = models.DateField(verbose_name='开始日期')
    duration = models.IntegerField(default=1, verbose_name='持续天数')
    # 工作日为0，公休日1，节假日2
    holidaytype = models.IntegerField(default=2, verbose_name='类型')
    quotient = models.IntegerField(default=2, verbose_name='系数')
    active = models.BooleanField(default=True, verbose_name='有效的')

    class Meta:
        db_table = 'att_holiday'


class classlist(models.Model):
    # 员工排班表 Schedule
    employeeid = models.ForeignKey('hr.employee', on_delete=models.CASCADE, verbose_name="员工ID")
    classid = models.ForeignKey('classes', on_delete=models.CASCADE, verbose_name='班次ID')
    datestart = models.DateField(blank=True, null=True, verbose_name='开始日期')
    dateend = models.DateField(blank=True, null=True, verbose_name='结束日期')
    adddate = models.DateTimeField(auto_now_add=True, verbose_name='新建时间')
    moddate = models.DateTimeField(auto_now=True, verbose_name='更新时间')
    active = models.BooleanField(default=True, verbose_name='有效的')

    class Meta:
        db_table = 'att_classlist'


class classes(models.Model):
    # 班次
    name = models.CharField(max_length=24, blank=True, null=True, verbose_name='班次')
    type = models.IntegerField(default=0, verbose_name='type')

    class Meta:
        db_table = 'att_classes'


class classsolt(models.Model):
    # 班次的时段
    classid = models.ForeignKey('classes', on_delete=models.CASCADE)
    timesoltid = models.ForeignKey('timesolt', on_delete=models.CASCADE)

    class Meta:
        db_table = 'att_classsolt'


class timesolt(models.Model):
    # 时段
    name = models.CharField(max_length=16, verbose_name='时段名')
    instar = models.TimeField(verbose_name='签到开始')
    intime = models.TimeField(verbose_name='签到时间')
    inend = models.TimeField(verbose_name='签到结束')
    incheck = models.BooleanField(default=True, verbose_name='必须签到')
    inlate = models.IntegerField(default=0, verbose_name='迟到')
    inabs = models.IntegerField(default=0, verbose_name='缺勤')
    outstar = models.TimeField(verbose_name='签到开始')
    outtime = models.TimeField(verbose_name='签到时间')
    outend = models.TimeField(verbose_name='签到结束')
    outcheck = models.BooleanField(default=True, verbose_name='必须签到')
    outleave = models.IntegerField(default=0, verbose_name='早退')
    outabs = models.IntegerField(default=0, verbose_name='缺勤')
    ckeckoneall = models.BooleanField(verbose_name='签到一次即为全勤')
    recday = models.IntegerField(default=1, verbose_name='记工作日')
    recminute = models.IntegerField(default=30, verbose_name='记工作时')
    lateif = models.BooleanField(default=False, verbose_name='迟到工时有效')
    latetime = models.IntegerField(default=30, verbose_name='迟到以内')
    sumworkhours = models.IntegerField(default=0, verbose_name='小计工时')
    adddate = models.DateTimeField(auto_now_add=True, verbose_name='新建时间')
    moddate = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        db_table = 'att_timesolt'


# class checkinout(models.Model):
#     # zktime8.5 db formate
#     userid = models.CharField(max_length=20, null=True, verbose_name='userid')
#     pin = models.CharField(max_length=20, blank=True, null=True, verbose_name='pin')
#     checktime = models.DateTimeField(blank=True, null=True, verbose_name='datatime')
#     checktype = models.CharField(max_length=5, blank=True, null=True, verbose_name='checktype')
#     verifycode = models.IntegerField(default=0, verbose_name='verifycode')
#     SN = models.CharField(max_length=20, blank=True, null=True, verbose_name='SN')
#     sensorid = models.CharField(max_length=5, blank=True, null=True, verbose_name='sensorid')
#     WorkCode = models.CharField(max_length=20, blank=True, null=True, verbose_name='WorkCode')
#     Reserved = models.CharField(max_length=20, blank=True, null=True, verbose_name='Reserved')
#     sn_name = models.CharField(max_length=40, blank=True, null=True, verbose_name='sn_name')
#
#     class Meta:
#         db_table = 'att_checkinout'


class checkinout(models.Model):
    # zktime5.0 db formate
    userid = models.IntegerField(default=0, verbose_name='userid')
    checktime = models.DateTimeField(blank=True, null=True, verbose_name='datatime')
    checktype = models.CharField(max_length=1, blank=True, null=True, verbose_name='checktype')
    verifycode = models.IntegerField(default=0, verbose_name='verifycode')
    sensorid = models.CharField(max_length=5, blank=True, null=True, verbose_name='sensorid')
    memoinfo = models.CharField(max_length=30, blank=True, null=True, verbose_name='memoinfo')
    workcode = models.CharField(max_length=20, blank=True, null=True, verbose_name='workcode')
    sn = models.CharField(max_length=20, blank=True, null=True, verbose_name='SN')
    userextfmt = models.SmallIntegerField(default=0, blank=True, null=True, verbose_name='userextfmt')
    pin = models.CharField(max_length=20, blank=True, null=True, verbose_name='pin')

    class Meta:
        db_table = 'att_checkinout'

attendance/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.db.models import Max, Min, Count

from attendance.models import extemployeeatt, holiday, classlist, classes, classsolt, timesolt, checkinout
from hr.models import employee

from . import msslqdb

import datetime
import time
import threading
from xml.etree.ElementTree import parse

# Create your views here.
def index(request):
    return redirect('/att/attendance/')


def attendance(request):
    context = {}
    context['title'] = '签到'

    if request.method == "GET":
        # print('get')
        if 'datecheck' in request.GET:
            datecheck = request.GET['datecheck']
            daytoday = datetime.datetime.strptime(datecheck, '%Y-%m-%d')
        else:
            daytoday = datetime.datetime.today()

        if "namecheck" in request.GET:
            employeename = request.GET['namecheck']
            if employeename == '':
                pass

        if 'departmentcheck' in request.GET:
            department = request.GET['departmentcheck']
            if department == '':
                pass

    context['daytoday'] = daytoday

    d = []
    pindicts= {}
    # 查找PIN
    # emppins = employee.objects.all() \
    emppins = employee.objects.exclude(extemployeeatt__pin=None) \
        .order_by('employee_department__departmentid__name', 'name')\
        .values('name', 'extemployeeatt__pin', 'employee_department__departmentid__name')
    print(len(emppins))
    for emppin in emppins:
        pindicts[emppin['extemployeeatt__pin']] = emppin
        print(emppin)

    # # 查找班次
    # ks = classlist.objects.all() \
    #     .values('id',
    #             'employeeid',
    #             'classid__name',
    #             'employeeid__extemployeeatt__pin',
    #             'datestart',
    #             'dateend') \
    #     .order_by('datestart')
    # print(ks)

    # 填写一览
    ps = checkinout.objects.filter(checktime__year=daytoday.year,
                                   checktime__month=daytoday.month,
                                   checktime__day=daytoday.day) \
        .values('pin') \
        .annotate(last=Max('checktime'), fast=Min('checktime'), count=Count('userid'))

    for p in ps:
        i = {}
        if p['pin'] in pindicts:
            i.update(pindicts[p['pin']])
        i.update(p)
        i['long'] = i['last'] - i['fast']
        d.append(i)
        # print(i)
    context['context2'] = d

    # ps = checkinout.objects.filter(checktime__year=daytoday.year,
    #                                checktime__month=daytoday.month,
    #                                checktime__day=daytoday.day,
    #                                pin=32).values().order_by('-checktime')
    # emppins = employee.objects.exclude(extemployeeatt__pin=None)\
    #     .order_by('employee_department__departmentid__name', 'name')\
    #     .values('name', 'extemployeeatt__pin', 'employee_department__departmentid__name')
    # pinsdict = {}
    # for i in emppins:
    #     pinsdict[i['extemployeeatt__pin']] = i
    #     del pinsdict[i['extemployeeatt__pin']]['extemployeeatt__pin']
    # p = []
    # for k in ps:
    #     if k['pin']:
    #         if k['pin'] in pinsdict:
    #             k.update(pinsdict[k['pin']])
    #     p.append(k)
    # context['context'] = p


    return render(request, 'att_attendance_list.html', context)


def summary(request):
    context={}
    context['title'] = '出勤'
    return render(request, 'att_summary_list.html', context)


def att_collect_detail(request):
    context={}
    context['title'] = '明细'
    return render(request, 'att_collect_detailed.html', context)


def attclass(request):
    context={}
    context['title'] = '班次'

    ps = classlist.objects.all()\
        .values('employeeid_id',
                 'employeeid__name',
                 'employeeid__employee_department__departmentid__name',
                 'employeeid__extemployeeatt__pin',
                 'classid__name',
                 'datestart',
                 'dateend',
                 'active').order_by('employeeid_id', 'employeeid__employee_department__departmentid__name', 'datestart')
    context['context'] = ps

    return render(request, 'att_class_board.html', context)


def attholiday(request):
    context={}
    context['title'] = '假期'
    return render(request, 'att_holiday_board.html', context)


def configatt(request):
    context={}
    context['title'] = '设置'
    return render(request, 'attendance_conf.html', context)


def institem(items=None):
    for userid, checktime, checktype, verifycode, sensorid, memoinfo, workcode, sn, userextfmt, logid, id in items:
        nitem = checkinout.objects.get_or_create(userid=userid,
                                                 checktime=checktime,
                                                 checktype=checktype,
                                                 verifycode=verifycode,
                                                 sensorid=sensorid,
                                                 memoinfo=memoinfo,
                                                 workcode=workcode,
                                                 sn=sn,
                                                 userextfmt=userextfmt)


def inputxml(request):
    with open('CHECKINOUT.XML', 'r', encoding="UTF-8") as f:
        et = parse(f)
    root = et.getroot()
    checkinouts = []
    for childone in root:
        item = []
        for childtwo in childone:
            item.append(childtwo.text)
            # print(childtwo.tag, ":", childtwo.text)
        checkinouts.append(item)
        # print(item)

    i = 0
    threads = []
    itemgroup = []
    for item in checkinouts:
        item.append(i)
        itemgroup.append(item)
        if (i % 2000) == 0:
            thread = threading.Thread(target=institem, args=(tuple(itemgroup),))
            threads.append(thread)
            itemgroup = []
        i += 1
    if itemgroup:
        thread = threading.Thread(target=institem, args=(tuple(itemgroup),))
        threads.append(thread)

    for threadrun in threads:
        threadrun.start()
    while True:
        if len(threading.enumerate()) <= 3:
            print('='*24)
            break
        time.sleep(5)
        print(len(threading.enumerate()))
    print('all done')

    with open('USERINFO.xml', 'r', encoding="UTF-8") as f:
        et = parse(f)
    root = et.getroot()
    checkinouts = []
    for childone in root:
        item = []
        for childtwo in childone:
            item.append(childtwo.text)
        checkinouts.append(item)
    for useritem in checkinouts:
        checkinouts = checkinout.objects.filter(userid=useritem[0])
        if checkinouts:
            checkinouts.update(pin=useritem[1])
        print(useritem[0], useritem[1], useritem[3], len(checkinouts))
        k = employee.objects.filter(name=useritem[3]).last()
        if k:
            l = extemployeeatt.objects.get_or_create(employeeid=k,
                                                     pin=useritem[1])
            print(l)
    return HttpResponse(len(checkinouts))


def checkeveryday(request):
    context = []
    body = 400
    daystart = datetime.datetime.strptime('2015-12-1', '%Y-%m-%d')
    dayend = datetime.datetime.strptime('2015-12-31', '%Y-%m-%d')

    eitems = checkinout.objects.filter(checktime__range=(daystart, dayend), userid=body).order_by('userid', 'checktime')
    context = eitems.values_list()
    # for i in eitems.values_list():
    #     print(i)
    lenday = dayend - daystart
    daytag = daystart
    while True:
        if daytag > dayend:
            break
        print(daytag)
        daytag += datetime.timedelta(days=1)

    print(lenday.days)
    print(daystart.year)
    print(daystart.month)
    print(daystart.day)
    print(len(eitems))

    # 方式
        #不打 为1
        #打   为1
        #和   为1
    # 设计班次
    # 天排班、周期
    # 人员周期内的排班表

    # 人员表
    # 计算得出每天状况
    # 产生全表
    # 汇总统计
    return HttpResponse(context)


def getmssql(request):
    import pymssql

    if request.method == "POST":
        if "days" in request.POST:
            # days = request.POST.get('days', '1')
            days = request.POST['days']

            days = int(days)
            dayfrom = datetime.datetime.today() - datetime.timedelta(days=days)

    dbsql = msslqdb.getmssqldb()
    conn = pymssql.connect(dbsql['server'], dbsql['user'], dbsql['password'], database=dbsql['database'])

    cursor = conn.cursor()
    strsql = "select * from CHECKINOUT where CHECKTIME >='" + dayfrom.strftime("%Y-%m-%d") + "'"
    cursor.execute(strsql)
    row = cursor.fetchone()
    crows = []
    while row:
        crows.append(row)
        row = cursor.fetchone()

    cursor = conn.cursor()
    cursor.execute('select * from userinfo')
    row = cursor.fetchone()
    prows = []
    while row:
        prows.append(row)
        row = cursor.fetchone()
    conn.close()

    uidpin = {}
    for prow in prows:
        uidpin[prow[0]] = prow[1]

    r = 0
    for userid, checktime, checktype, verifycode, sensorid, memoinfo, workcode, sn, userextfmt in crows:
        nitem = checkinout.objects.get_or_create(userid=userid,
                                                 checktime=checktime,
                                                 checktype=checktype,
                                                 verifycode=verifycode,
                                                 sensorid=sensorid,
                                                 memoinfo=memoinfo,
                                                 workcode=workcode,
                                                 sn=sn,
                                                 userextfmt=userextfmt,
                                                 pin=uidpin[userid])
        m, n = nitem
        if n:
            r += 1
    return HttpResponse(" 更新记录:" + str(r))


def getmssqlpin(request):
    import pymssql

    dbsql = msslqdb.getmssqldb()

attendance/templates/att_attendance_list.html
{% extends "base.html" %}

{% block styecss %}

{% endblock styecss %}

{% block mainbody %}
<div class="container-fluid">
    <div class="row mt-3">
        <div class="col-2 border-right">
            {% include 'hr_sub_sidemenu.html' %}
        </div>
        <div class="col-10">
            <div class="row border-bottom">
                <div class="col-12">
                    <div class="row">
                        <h3 class="col-auto mr-auto">{{ title }}</h3>
                        <div class="col-auto px-0">
                            <form class="form-inline mb-2" action=" {% url 'attendance:attendance' %}" method="get" >
                                <label class="col-form-label mr-2" for="datecheck">日期</label>
                                <input class="form-control mr-2" type="date" name="datecheck" id="datecheck" value="{{ daytoday| date:"Y-m-d" }}">
                                <label class="col-form-label mr-2 sr-only" for="departmentcheck">部门</label>
                                <input class="form-control mr-2" type="text" name="departmentcheck" id="departmentcheck" value="" placeholder="(部门)">
                                <label class="col-form-label mr-2 sr-only" for="namecheck">姓名</label>
                                <input class="form-control mr-2" type="text" name="namecheck" id="namecheck" value="" placeholder="(人员)">
                                <button type="submit" class="btn btn-primary mr-2" data-toggle="query">查询</button>
                            </form>
                        </div>
                        <div class="col-auto">
                            <div class="btn-group" role="group">
                                <button id="btnGroupDrop1" type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="runstatus sr-only spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                                    <span class="runstatus sr-only">获取中...</span>
                                    <span class="runstatus">获取记录</span>
                                </button>
                                <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                                    <a class="run dropdown-item" href="#" data-action="1">获取记录(1d)</a>
                                    <a class="run dropdown-item" href="#" data-action="3">获取记录(3d)</a>
                                    <a class="run dropdown-item" href="#" data-action="7">获取记录(7d)</a>
                                    <a class="run dropdown-item" href="#" data-action="30">获取记录(30d)</a>
                                    <a class="run dropdown-item" href="#" data-action="60">获取记录(60d)</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 p-0">
                    <table class="table table-hover mb-0">
                        <thead class="bg-light">
                            <tr>
                                <th class="border-right" data-id="sid">姓名<i class="" aria-hidden="true" data-id="0"></i></th>
                                <th class="border-right" data-id="sid">PIN<i class="" aria-hidden="true" data-id="0"></i></th>
                                <th class="border-right" data-id="name">部门<i class="fa fa-sort-alpha-asc" aria-hidden="true" data-id="1"></i></th>
                                <th class="border-right" data-id="name">规则<i class="" aria-hidden="true" data-id="1"></i></th>
                                <th class="border-right" data-id="specifications">最早<i class="" aria-hidden="true" data-id="0"></i></th>
                                <th class="border-right" data-id="specifications">最晚<i class="" aria-hidden="true" data-id="0"></i></th>
                                <th class="border-right" data-id="name">次数<i class="" aria-hidden="true" data-id="1"></i></th>
                                <th class="border-right" data-id="warranty">工时<i class="" aria-hidden="true" data-id="0"></i></th>
                                <th class="border-right" data-id="sn">审批单<i class="" aria-hidden="true" data-id="0"></i></th>
                                <th class="border-right" data-id="sn">状态<i class="" aria-hidden="true" data-id="0"></i></th>
                                <th class="text-right" data-id="act"><i class="fa fa-align-justify" aria-hidden="true" data-id="0"></i></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in context2 %}
                                <tr>
                                    <th>{{ item.name }}</th>
                                    <td>{{ item.pin}}</td>
                                    <td>{{ item.employee_department__departmentid__name }}</td>
                                    <td>白天班</td>
                                    <td>{{ item.fast | date:"H:i" }}</td>
                                    <td>{{ item.last | date:"H:i" }}</td>
                                    <td>{{ item.count| default:"-"}}</td>
                                    <td>{{ item.long | default:"-"}}</td>
                                    <td>2</td>
                                    <td>OK</td>
                                    <td class="detailattendance text-right text-muted" data-val="{{ item.pin }}"><i class="fa fa-list" aria-hidden="true" data-id="0"></i></td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="11" style="text-align: center;">(暂无数据)</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- 出勤个人详细对话框 -->
    <div class="modal fade" id="imglist" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="myModalLabel">详细: XXXX(2019-5-3)</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">

                    <table class="table table-hover table-sm">
                        <thead class="bg-light">
                            <tr>
                                <th class="border-right" data-id="sid">姓名<i class="" aria-hidden="true" data-id="0"></i></th>
                                <th class="border-right" data-id="name">部门<i class="" aria-hidden="true" data-id="1"></i></th>
                                <th class="border-right" data-id="name">PIN<i class="" aria-hidden="true" data-id="1"></i></th>
                                <th class="border-right" data-id="specifications">时间<i class="fa fa-sort-alpha-desc" aria-hidden="true" data-id="0"></i></th>
                                <th class="border-right" data-id="sn">方式<i class="" aria-hidden="true" data-id="0"></i></th>
                                <th class="border-right" data-id="sn">来源<i class="" aria-hidden="true" data-id="0"></i></th>
                                <th class="border-right" data-id="sn">校准<i class="" aria-hidden="true" data-id="0"></i></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in context %}
                                <tr>
                                    <th>{{ item.name | title }}</th>
                                    <td>{{ item.employee_department__departmentid__name }}</td>
                                    <td>{{ item.pin| default_if_none:'-' }}</td>
                                    <td>{{ item.checktime | date:"Y-m-d H:i:s" }}</td>
                                    <td>{{ item.count| default:"-"}}</td>
                                    <td>{{ item.sn | default_if_none:'-' }}</td>
                                    <td>设备</td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="10" style="text-align: center;">(暂无数据)</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block jquery %}
    <script type="text/javascript">
        $(document).ready(function(){
            $(".run").click(function(){
                $('.runstatus').toggleClass('sr-only');
                $('#btnGroupDrop1').attr("disabled", "1");
                days = $(this).attr('data-action');
                $.post(
                    "/att/getmssql/",
                    {'days': days},
                    function(data){
                        $('.runstatus').toggleClass('sr-only');
                        $('#btnGroupDrop1').removeAttr("disabled");
                        console.log(data)
                    });
            });

            $(".detailattendance").click(function () {
                $('#imglist').modal('show');
                console.log($(this).attr('data-val'));
                console.log($('#datecheck').val());
            });
        });
    </script>
{% endblock jquery%}

attendance/templates/att_holiday_board.html
{% extends "base.html" %}

{% block styecss %}

{% endblock styecss %}

{% block mainbody %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-2 border-right">
                {% include 'hr_sub_sidemenu.html' %}
            </div>
            <div class="col-10">
                <div class="row border-bottom mb-3">
                    <div class="col-12">
                        <div class="row">
                            <h3 class="col-sm-6">{{ title }}</h3>
                        </div>
                        <div class="row mb-2">
                            <div class="col-12">
                                <button type="button" class="btn btn-primary" data-toggle="create" id="kkkk">保存</button>
                                <button type="button" class="btn btn-outline-secondary disabled" data-toggle="del">返回</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    {% include 'hr_sub_toast.html' %}
{% endblock %}

{% block jquery %}
{#        <script src="/static/js/hr/view_hr_broad.js"></script>#}
{% endblock jquery%}